# Generated by Django 3.1.7 on 2022-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modified_date',
            new_name='exp_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='mfg_date',
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
