# Generated by Django 3.1.7 on 2022-03-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220318_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfg_date',
        ),
        migrations.AddField(
            model_name='product',
            name='EXP_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='MFG_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
